-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- PROFILES (Extends Auth)
-- V1 -> V2 Migration: Add columns if they don't exist
alter table profiles 
  add column if not exists deep_work_mode boolean default false,
  add column if not exists active_sprint boolean default false,
  add column if not exists streak integer default 0,
  add column if not exists xp integer default 0,
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists plan_tier text default 'free',
  add column if not exists subscription_status text;

-- SPRINTS (90-Day Acceleration)
create table if not exists sprints (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references profiles(id) on delete cascade not null,
  target_role text not null,
  primary_skill_focus text not null,
  primary_project_focus text not null,
  sprint_cycle_number integer default 1,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  status text check (status in ('active', 'cooldown', 'completed', 'abandoned')) default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- LOGS (Daily Entries)
-- V1 -> V2 Migration: Add sprint tracking to logs
alter table logs
  add column if not exists sprint_id uuid references sprints(id) on delete set null;

-- SKILLS
create table if not exists skills (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  category text, 
  current_level integer default 1 check (current_level between 1 and 5),
  target_level integer default 5 check (target_level between 1 and 5),
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- PROJECTS
create table if not exists projects (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  status text check (status in ('Idea', 'Build', 'Polish', 'Ship', 'Archived')),
  tech_stack text[],
  github_url text,
  demo_url text,
  hire_signal boolean default false,
  checklist jsonb default '{"readme": false, "demo": false, "metrics": false, "social": false}'::jsonb,
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- APPLICATIONS
create table if not exists applications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  company text not null,
  role text,
  platform text,
  date_applied date,
  status text check (status in ('Applied', 'OA Received', 'Interview', 'Offer', 'Rejected')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- SPRINT METRICS (AccelerationScore Snapshots)
create table if not exists sprint_metrics (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references profiles(id) on delete cascade not null,
  sprint_id uuid references sprints(id) on delete cascade not null,
  week_number integer not null,
  acceleration_score numeric not null,
  execution_consistency numeric not null,
  deep_work_hours numeric not null,
  roadmap_completion numeric not null,
  skill_delta numeric not null,
  snapshot_date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table sprints enable row level security;
alter table logs enable row level security;
alter table skills enable row level security;
alter table projects enable row level security;
alter table applications enable row level security;
alter table sprint_metrics enable row level security;

-- Policies (Drop if exists to avoid collision, then create)
DO $$
BEGIN
    DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON profiles;
    DROP POLICY IF EXISTS "Users can insert their own profile." ON profiles;
    DROP POLICY IF EXISTS "Users can update own profile." ON profiles;

    DROP POLICY IF EXISTS "Users can view own sprints." ON sprints;
    DROP POLICY IF EXISTS "Users can insert own sprints." ON sprints;
    DROP POLICY IF EXISTS "Users can update own sprints." ON sprints;

    DROP POLICY IF EXISTS "Users can view own logs." ON logs;
    DROP POLICY IF EXISTS "Users can insert own logs." ON logs;
    DROP POLICY IF EXISTS "Users can update own logs." ON logs;

    DROP POLICY IF EXISTS "Users can view own skills." ON skills;
    DROP POLICY IF EXISTS "Users can insert own skills." ON skills;
    DROP POLICY IF EXISTS "Users can update own skills." ON skills;

    DROP POLICY IF EXISTS "Users can view own projects." ON projects;
    DROP POLICY IF EXISTS "Users can insert own projects." ON projects;
    DROP POLICY IF EXISTS "Users can update own projects." ON projects;

    DROP POLICY IF EXISTS "Users can view own applications." ON applications;
    DROP POLICY IF EXISTS "Users can insert own applications." ON applications;
    DROP POLICY IF EXISTS "Users can update own applications." ON applications;

    DROP POLICY IF EXISTS "Users can view own sprint metrics." ON sprint_metrics;
END $$;

create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Users can view own sprints." on sprints for select using ( auth.uid() = user_id );
create policy "Users can insert own sprints." on sprints for insert with check ( auth.uid() = user_id );
create policy "Users can update own sprints." on sprints for update using ( auth.uid() = user_id );

create policy "Users can view own logs." on logs for select using ( auth.uid() = user_id );
create policy "Users can insert own logs." on logs for insert with check ( auth.uid() = user_id );
create policy "Users can update own logs." on logs for update using ( auth.uid() = user_id );

create policy "Users can view own skills." on skills for select using ( auth.uid() = user_id );
create policy "Users can insert own skills." on skills for insert with check ( auth.uid() = user_id );
create policy "Users can update own skills." on skills for update using ( auth.uid() = user_id );

create policy "Users can view own projects." on projects for select using ( auth.uid() = user_id );
create policy "Users can insert own projects." on projects for insert with check ( auth.uid() = user_id );
create policy "Users can update own projects." on projects for update using ( auth.uid() = user_id );

create policy "Users can view own applications." on applications for select using ( auth.uid() = user_id );
create policy "Users can insert own applications." on applications for insert with check ( auth.uid() = user_id );
create policy "Users can update own applications." on applications for update using ( auth.uid() = user_id );

-- Server controls metric insertions, users only select.
create policy "Users can view own sprint metrics." on sprint_metrics for select using ( auth.uid() = user_id );

-- TRIGGERS
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, role, level)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'role', new.raw_user_meta_data->>'level')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger first to avoid errors
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
