
-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- PROFILES (Extends Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  role text,
  level text,
  avatar_url text,
  deep_work_mode boolean default false,
  streak integer default 0,
  xp integer default 0,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- LOGS (Daily Entries)
create table logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date date not null,
  hours_studied numeric default 0,
  focus_area text,
  tasks_completed integer default 0,
  deep_work_intervals integer default 0,
  mood text,
  blockers text,
  shipped_today text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SKILLS
create table skills (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  category text, 
  current_level integer default 1 check (current_level between 1 and 5),
  target_level integer default 5 check (target_level between 1 and 5),
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- PROJECTS
create table projects (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  status text check (status in ('Idea', 'Build', 'Polish', 'Ship', 'Archived')),
  tech_stack text[],
  github_url text,
  demo_url text,
  hire_signal boolean default false,
  checklist jsonb default '{"readme": false, "demo": false, "metrics": false, "social": false}'::jsonb,
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- APPLICATIONS
create table applications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  company text not null,
  role text,
  platform text,
  date_applied date,
  status text check (status in ('Applied', 'OA Received', 'Interview', 'Offer', 'Rejected')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table logs enable row level security;
alter table skills enable row level security;
alter table projects enable row level security;
alter table applications enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Users can view own logs." on logs for select using ( auth.uid() = user_id );
create policy "Users can insert own logs." on logs for insert with check ( auth.uid() = user_id );
create policy "Users can update own logs." on logs for update using ( auth.uid() = user_id );

create policy "Users can view own skills." on skills for select using ( auth.uid() = user_id );
create policy "Users can insert own skills." on skills for insert with check ( auth.uid() = user_id );
create policy "Users can update own skills." on skills for update using ( auth.uid() = user_id );

create policy "Users can view own projects." on projects for select using ( auth.uid() = user_id );
create policy "Users can insert own projects." on projects for insert with check ( auth.uid() = user_id );
create policy "Users can update own projects." on projects for update using ( auth.uid() = user_id );

create policy "Users can view own applications." on applications for select using ( auth.uid() = user_id );
create policy "Users can insert own applications." on applications for insert with check ( auth.uid() = user_id );
create policy "Users can update own applications." on applications for update using ( auth.uid() = user_id );

-- TRIGGERS
-- Handle new user creation
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, role, level)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'role', new.raw_user_meta_data->>'level');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
